### ISSUE TITLE
Welcome to SEBC, take two

### ISSUE THREAD

**Issue by mfernest** [fahad85/SEBC#1]
Thanks for the repo name change -- it will save me a lot of time.

I haven't seen your labels updated yet, but sometimes GitHub is slow to propagate the changes. Please do make sure your labels conform to the guidelines in `README.md` if you haven't already.

Also be sure @cpiva accepts your invitation to collaborate.

When these tasks are complete you can close this Issue

**Comment by fahad85** [comment]
Labels have been updated according to the guideline document, Awaiting Carlo's acceptance of the invite.

**Comment by fahad85** [comment]
Carlo has accepted the invitation to collaborate. Closing the issue now.
