### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by fahad85** [fahad85/SEBC#2]

**Comment by fahad85** [comment]
Completed the CM installation lab and changed the status from started to submitted.

**Comment by mfernest** [comment]
`1_preinstall.md` - I'm not sure why you chose to list commands you used but didn't show their results. As with any exercise, you should want to know what output to expect.

**Comment by mfernest** [comment]
`2_cm_installation.md` - same

**Comment by mfernest** [comment]
`2_replica_working.md` - lots here, but not what I asked for: output to show slave replication is working (`SHOW SLAVE STATUS \G`).

**Comment by mfernest** [comment]
CM console up and running.
