### ISSUE TITLE
Storage Labs

### ISSUE THREAD

**Issue by fahad85** [fahad85/SEBC#3]

**Comment by fahad85** [comment]
Cloudera Manager URL
http://54.252.147.158:7180/cmf/

**Comment by fahad85** [comment]
distcp was failing due to space issues on the filesystem

**Comment by mfernest** [comment]
`0_replication.md` -- good work, but you could also track down the relevant logs (they're listed in the distcp job output) and get closer to the source of the problem.

**Comment by mfernest** [comment]
`1_terasort_tests.md` - since HDFS files cannot be modified, you cannot overwrite them. You can only delete them and write them again. This applies to directories as well as files.

**Comment by mfernest** [comment]
I understand the expedience of screen shots for capturing job output, but it is considerably harder to read and comment.
