### ISSUE TITLE
YARN Labs

### ISSUE THREAD

**Issue by fahad85** [fahad85/SEBC#4]

**Comment by mfernest** [comment]
The summary you posted in `2_YARN_Static_Pools.md` I think would have been appropriate as a comment here. What I asked for evidence of the work in the lab files. I trust that you did what you said you did, but I can't evaluate what I can't see.

**Comment by mfernest** [comment]
The job script uses the option `--skipTrash` to delete the files created. This suggests to me your disks were near capacity when you started.
